Nbc update db
MediaComem/modos pull request #43
Opened 2020-10-29 12:03 UTC by nicolas-heigvd

All your bases are belong to us...

2020-10-29 15:07 UTC, nicolas-heigvd commented
@verdonarthur Fixed ?

2020-10-29 15:52 UTC, verdonarthur requested changes
Fix the line jump and see with @AlphaHydrae to resolve the other problem with osmdata schema

2020-10-29 15:52 UTC, verdonarthur commented on packages/backend/src/migration/1603879411988-initDomains.ts
> +}
missing line jump

2020-10-29 15:52 UTC, verdonarthur commented on packages/backend/src/migration/1603887777590-initSpatialRel.ts
> +}
Missing line jump

2020-10-29 15:52 UTC, verdonarthur commented on packages/backend/src/migration/1603887777592-alterTables.ts
> +}
missing line jump

2020-10-30 11:34 UTC, nicolas-heigvd commented
I hope it can be merged now, everything is schema agnostic; it's a big mix in the public schema by default.

Be careful; the postgis spatial reference table is nearby the application tables. Do not touch it!

2020-10-30 14:28 UTC, verdonarthur approved these changes
Not sure to understand all the modification you are doing but it's ok for me

2020-11-05 08:15 UTC, merged